# Generated by Django 5.1.4 on 2025-01-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_is_paid_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payu_order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payu_payment_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payu_signature',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
