# Generated by Django 4.2.17 on 2025-01-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_payu_order_id_order_payu_payment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payu_payment_id',
            new_name='payment_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payu_signature',
            new_name='signature',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payu_order_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
