# Generated by Django 4.2.17 on 2025-01-09 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_checkout_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payu_payment_id',
            new_name='payment_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payu_order_id',
            new_name='payment_order_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payu_signature',
            new_name='payment_signature',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_signature',
        ),
    ]
