# Generated by Django 4.2.17 on 2025-01-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_payu_payment_id_order_payment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_signature',
            new_name='payu_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment_order_id',
            new_name='payu_order_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment_id',
            new_name='payu_signature',
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
