# Generated by Django 4.2.17 on 2025-01-27 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_payment_signature_order_payu_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payu_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payu_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payu_signature',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
